[package]
name = "rs-pancat-paths"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.33"
indexmap = "2.6.0"
petgraph = "0.7.1"
clap = { version = "4.0", features = ["derive"] }